### ISSUE TITLE
Have to run groupadd docker after install, else docker.socket fails to start

### ISSUE THREAD

**Issue by DJFliX** [Mhynlo/readynas-docker-cli#1] opened 2017-06-24 11:22 UTC
The title says it all :). 

```|bash
root@ReadyNAS:~# systemctl status docker.socket
● docker.socket - Docker Socket for the API
   Loaded: loaded (/lib/systemd/system/docker.socket; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2017-06-24 13:03:51 CEST; 7min ago
   Listen: /var/run/docker.sock (Stream)

Jun 24 13:03:51 ReadyNAS systemd[1]: Starting Docker Socket for the API.
Jun 24 13:03:51 ReadyNAS systemd[1]: docker.socket: Control process exited, code=exited status=216
Jun 24 13:03:51 ReadyNAS systemd[1]: Failed to listen on Docker Socket for the API.
Jun 24 13:03:51 ReadyNAS systemd[1]: docker.socket: Unit entered failed state.

root@ReadyNAS:~# cat /etc/group | grep docker
Pattern not found

root@ReadyNAS:~# groupadd docker

root@ReadyNAS:~# systemctl start docker.socket

root@ReadyNAS:~# systemctl status docker.socket
● docker.socket - Docker Socket for the API
   Loaded: loaded (/lib/systemd/system/docker.socket; disabled; vendor preset: enabled)
   Active: active (listening) since Sat 2017-06-24 13:11:30 CEST; 9min ago
   Listen: /var/run/docker.sock (Stream)

Jun 24 13:11:30 ReadyNAS systemd[1]: Starting Docker Socket for the API.
Jun 24 13:11:30 ReadyNAS systemd[1]: Listening on Docker Socket for the API.`
```

Could you add the groupadd statement as part of the install script?

**Comment by Mhynlo** [comment] 2017-06-27 00:57
I noticed the docker group added on most of my installs.
Let me see if I am able to reproduce the issue.

I think it is handled in the docker-ce package. I will double check that package to see if that is where the groupadd is effecting my units or if it is coming from somewhere else.

**Comment by Mhynlo** [comment] 2017-06-27 01:30
It looks like the docker-ce includes the group in their postinst:
```bash
if ! getent group docker > /dev/null; then
	groupadd --system docker
fi
```

What version of the docker-cli-rnapp are you running?

**Comment by DJFliX** [comment] 2017-06-27 06:03
I'm using your latest release: https://github.com/Mhynlo/readynas-docker-cli/releases/download/17.03/docker-cli-rnapp_17.03.0_amd64.deb

Thanks for checking :).

**Comment by Mhynlo** [comment] 2017-07-01 22:05
Closing this issue since the dependent package handles the `docker` group.

**Closed as completed by Mhynlo** 2017-07-01 22:05 UTC
